version: '3.8'

services:
  postgres:
    container_name: postgres_dev
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"   # PostgreSQL default port (Only Exposed for dev)
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/1-init_db.sql:ro
      - ./scripts/core_migration.sql:/docker-entrypoint-initdb.d/2-core_migrations.sql:ro
      - ./scripts/airline_alliances.sql:/docker-entrypoint-initdb.d/3-airline_alliances.sql:ro
    networks:
      - internal
    restart: unless-stopped

  flighttime:
    container_name: flighttime
    build:
      context: ./flightTime
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - internal
    restart: unless-stopped

volumes:
  pgdata-dev:

networks:
  internal:
    driver: bridge