version: '3.8'

services:
  meridian:
    container_name: meridian
    image: aboveu/meridian:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - flighttime
    networks:
      - internal
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/1-init_db.sql:ro
      - ./scripts/core_migration.sql:/docker-entrypoint-initdb.d/2-core_migrations.sql:ro
      - ./scripts/airline_alliances.sql:/docker-entrypoint-initdb.d/3-airline_alliances.sql:ro
    networks:
      - internal
    restart: unless-stopped

  flighttime:
    container_name: flighttime
    build:
      context: ./flightTime
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - internal
    restart: unless-stopped

volumes:
  pgdata:

networks:
  internal:
    driver: bridge