version: '3.8'

services:
  meridian:
    container_name: meridian
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - internal
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

volumes:
  pgdata:

networks:
  internal:
    driver: bridge